### ISSUE TITLE
initialValue field, in definePathname schema, does not work in Pages view

### ISSUE THREAD

**Issue by tamaccount** [tinloof/sanity-kit#22]
Hi, I'm having a problem where the `initialValue` field is not working properly when I'm in the `Pages` view.

Setting the `initialValue` within the `definePathname` schema argument seems to only have an effect in the `Schema` view, but not the `Pages` view
```
definePathname({
  name: "pathname",
  initialValue: {
    current: '/authors/',
  },
  options: {
    i18n: {
      enabled: true,
      defaultLocaleId: config.i18n.defaultLocaleId,
    },
  },
}),
```
![initialValue](https://github.com/tinloof/sanity-kit/assets/15708264/600f08e6-31c1-4d82-b1a8-1f510fb4490d)

**Comment by Jamiewarb** [comment]
This is because the slug field is initialised to the current directory when using it from Pages view

I was considering how this could be improved, as you may have certain page types that should initialised with a certain slug.

For example, I'm working on a large site for a global charity, and they have Factsheets which should always come under `/factsheets` when clicking New from the menu. Current implementation would mean the user has to ensure they are in the factsheets directory, or change the slug to factsheets.

Worth a convo to chat about this and what the package maintainers may be open to

**Comment by tamaccount** [comment]
Hi @Jamiewarb.

Yeah, I saw your issue, https://github.com/tinloof/sanity-kit/issues/21, and to me, it is somewhat relevant to mine. I agree that it should be easy to change the pathname for all of the pages inside a folder.

When it comes to your suggestions, I think `1a` would be the best.  Having a locked/uneditable part of the slug would prevent non-technical users from accidentally changing the parent folder. 

For option `3`, removing these schemas from the Pages view, this is not ideal, because it prevents users from being accessing the live preview.   

---

And thanks for pointing out the code in `src/plugins/navigator/components/Header.tsx`. I didn't realize this was the issue, and that it was overwriting my `initialValue` option. Hopefully the package maintainers can make a change here

**Comment by tamaccount** [comment]
closing this issue; no longer seems to be occurring, since merge of https://github.com/tinloof/sanity-kit/pull/32

**Comment by tamaccount** [comment]
nevermind. i should not have closed this. 

lol, im not sure how/why, in the video here, https://github.com/tinloof/sanity-kit/issues/36, the `initialValue` option seemed to be working. but it's not working now. 

so this actually does need to be addressed

**Comment by thomasKn** [comment]
Hey @tamaccount could you give `v1.1.3` a try?
